seed: 13086
use_gpu: True
gpu_idx: 0

logging: True
log_dir: '../../autodl-tmp/ml_logs_2/'
exp: 'exp-spf'


dataset_info_path: '../../autodl-tmp/ml_data/dataset_0.json'
data_root_path: '../../autodl-tmp/ml_data/RawData'
embedded: True
num_classes: 13
num_workers: 0
batch_size: 32
img_input_size: [1024, 1024]

model_type: 'vit_h'
model_root_path: '../../autodl-tmp/ml_model'
model_checkpoint: 'sam_vit_h_4b8939.pth'
multimask: True

prompt_type: 'single_point'
prompt_choice: 'center'
prompt_num: 8
grid_num: 32 
box_padding: 0

mode: 'train'
model_path: ''
max_epoch: 10
save_epoch: 11
lr: 1.5e-4
wd: 1.e-3
lr_decay: True
warm_up: True
warm_up_steps: 200
lr_scheduler: 'cosine'
lr_scheduler_gamma: 0.5
lr_scheduler_step_size: 500
optimizer: 'AdamW'
focal_alpha: 0.25
focal_gamma: 2.
dice_weight: 0.1
dice_p: 1.
dice_smooth: 1.
iou_weight: 0.
subset_valid: False